### ISSUE TITLE
Xfinity bot detection

### ISSUE THREAD

**Issue by ericmei** [jakehilborn/debbit#25]
It seems that Xfinity now refuses log-in via error message of incorrect login/password, if firefox is on remote control 

Can you add support to go directly to payments page without trying to log in again, if the user is currently already logged in?

**Comment by jakehilborn** [comment]
Ah you're right, I was able to confirm on my machine as well. I found a workaround so I'll try to get a release out tonight that fixes it. Definitely by this weekend if I can't get tonight.

Yes, technically, debbit could point to the Firefox profile you already use. But even if you're already logged in, at some point in the future Xfinity is going to ask for your username/password again. To make your existing profile work you'd have to download a custom add-on beforehand. This add-on is shipped with Debbit and doesn't even exist in the Firefox add-ons site yet. This particular issue is solved by just changing the user agent.

**Comment by jakehilborn** [comment]
@ericmei Are you running from source or one of the downloads from the release tab? Mac, windows, or linux? I'd like to send you a test version and have you verify that it fixes the problem.

**Comment by ericmei** [comment]
Downloaded the windows release. 

Sure send it when you get a chance

**Comment by jakehilborn** [comment]
I put together a fix. It works for my account on both my laptop and a server on a different network.

[debbit_2.0.1_xfinity_patch.zip](https://github.com/jakehilborn/debbit/files/4828667/debbit_2.0.1_xfinity_patch.zip)

Try downloading this zip which contains `debbit.exe` and `xfinity_bill_pay.py`. On your computer, stop debbit if it is running. Replace `debbit.exe` with the one from this patch, and replace `program_files\merchants\xfinity_bill_pay.py` with the one from this patch.

Also, if Xfinity made you change your password due to the bot detection, make sure you have your latest password in the config file! If this patch works for you I'll release it as debbit v2.0.1.

**Comment by ericmei** [comment]
It works for me! Thanks for the good work :)

**Comment by jakehilborn** [comment]
Nice, I'll put out a release. Thanks for reporting the bug and testing the fix.

**Comment by jakehilborn** [comment]
Fixed in [Debbit v2.0.1](https://github.com/jakehilborn/debbit/releases)
