### ISSUE TITLE
OSError: [Errno 22] Invalid Argument

### ISSUE THREAD

**Issue by dallasbest1** [jakehilborn/debbit#28]
Seems it's getting hung up starting the script.  I've attached all the text from when it runs.  No failures folder.

C:\Users\Austin\Desktop\Files\Debbit>debbit.exe
INFO: 2020-06-30 10:53:10,665        __     __    __    _ __
INFO: 2020-06-30 10:53:10,665   ____/ /__  / /_  / /_  (_) /_
INFO: 2020-06-30 10:53:10,666  / __  / _ \/ __ \/ __ \/ / __/
INFO: 2020-06-30 10:53:10,666 / /_/ /  __/ /_/ / /_/ / / /_
INFO: 2020-06-30 10:53:10,666 \__,_/\___/_.___/_.___/_/\__/  v2.0.1
INFO: 2020-06-30 10:53:10,666
INFO: 2020-06-30 10:53:10,784 No purchases yet complete for June 2020
INFO: 2020-06-30 10:53:10,784
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "debbit.py", line 134, in burst_loop
  File "debbit.py", line 158, in log_next_burst_time
OSError: [Errno 22] Invalid argument

Press any key to close this window...

**Comment by jakehilborn** [comment]
Can you past your config.txt here? Please remove your username, password, email, and card details.

**Comment by dallasbest1** [comment]
mode: burst
hide_web_browser: no
notify_failure: worst.david@gmail.com

bank_card: 
  amazon_gift_card_reload:
    total_purchases: 8
    amount_min: 50
    amount_max: 59
    usr: 
    psw: 
    card: 
    burst_count: 2

**Comment by dallasbest1** [comment]
It's now the first of the month and I'm running it and not getting the same issue.  Do you think it may of been because I initiated it the first time on the 30th of a month?

**Comment by jakehilborn** [comment]
Which version of Windows are you using? Windows 7? Windows 10? etc.

I did a bit of digging and it looks like some of the timestamp math that involves any timestamp with the value zero throws an error on Windows. Debbit runs purchases between the first day of the month and the day before the last day of the month. Since you ran it on the last day, it probably ran into some timestamp error.

Thanks for the additional info though. I'll try to reproduce this error on Windows and fix it.

**Comment by dallasbest1** [comment]
That makes sense.  I'm running Windows 10.

**Comment by jakehilborn** [comment]
[Debbit v2.1](https://github.com/jakehilborn/debbit/releases) has been released which has fixed this issue.
